export const difficultyProfiles = [
  {
    id: 'baby',
    name: 'Baby',
    rivalCompanyCount: 1,
    description: 'A forgiving learning mode with low costs, slow rivals, and generous operating margins.',
    multipliers: {
      researchCost: 0.55,
      researchTime: 0.6,
      rawSupplyCost: 0.7,
      refinedSupplyCost: 0.75,
      supplierContractCost: 0.7,
      productionOverhead: 0.65,
      employeeLaborCost: 0.65,
      engineerLaborCost: 0.65,
      efficiencyPenalty: 0.45,
      maintenanceBurden: 0.55,
      defectPressure: 0.5,
      rivalResearchSpeed: 0.55,
      rivalMarketPressure: 0.45,
      rivalAggression: 0.35,
    },
  },
  {
    id: 'easy',
    name: 'Easy',
    rivalCompanyCount: 2,
    description: 'A softer business environment with reduced pressure and fewer aggressive competitors.',
    multipliers: {
      researchCost: 0.78,
      researchTime: 0.8,
      rawSupplyCost: 0.85,
      refinedSupplyCost: 0.88,
      supplierContractCost: 0.85,
      productionOverhead: 0.82,
      employeeLaborCost: 0.8,
      engineerLaborCost: 0.82,
      efficiencyPenalty: 0.72,
      maintenanceBurden: 0.78,
      defectPressure: 0.75,
      rivalResearchSpeed: 0.75,
      rivalMarketPressure: 0.72,
      rivalAggression: 0.68,
    },
  },
  {
    id: 'normal',
    name: 'Normal',
    rivalCompanyCount: 3,
    description: 'The baseline tuning target for campaign and sandbox balance.',
    multipliers: {
      researchCost: 1,
      researchTime: 1,
      rawSupplyCost: 1,
      refinedSupplyCost: 1,
      supplierContractCost: 1,
      productionOverhead: 1,
      employeeLaborCost: 1,
      engineerLaborCost: 1,
      efficiencyPenalty: 1,
      maintenanceBurden: 1,
      defectPressure: 1,
      rivalResearchSpeed: 1,
      rivalMarketPressure: 1,
      rivalAggression: 1,
    },
  },
  {
    id: 'hard',
    name: 'Hard',
    rivalCompanyCount: 4,
    description: 'A tighter market with higher operating costs and more competitive rivals.',
    multipliers: {
      researchCost: 1.18,
      researchTime: 1.15,
      rawSupplyCost: 1.12,
      refinedSupplyCost: 1.15,
      supplierContractCost: 1.14,
      productionOverhead: 1.16,
      employeeLaborCost: 1.12,
      engineerLaborCost: 1.14,
      efficiencyPenalty: 1.2,
      maintenanceBurden: 1.18,
      defectPressure: 1.14,
      rivalResearchSpeed: 1.15,
      rivalMarketPressure: 1.2,
      rivalAggression: 1.18,
    },
  },
  {
    id: 'difficult',
    name: 'Difficult',
    rivalCompanyCount: 5,
    description: 'A punishing industrial market where rivals move quickly and mistakes become expensive.',
    multipliers: {
      researchCost: 1.38,
      researchTime: 1.32,
      rawSupplyCost: 1.25,
      refinedSupplyCost: 1.3,
      supplierContractCost: 1.28,
      productionOverhead: 1.35,
      employeeLaborCost: 1.24,
      engineerLaborCost: 1.28,
      efficiencyPenalty: 1.45,
      maintenanceBurden: 1.4,
      defectPressure: 1.35,
      rivalResearchSpeed: 1.32,
      rivalMarketPressure: 1.45,
      rivalAggression: 1.4,
    },
  },
  {
    id: 'insane',
    name: 'Insane',
    rivalCompanyCount: 6,
    description: 'A hostile market with severe costs, fast rivals, and narrow margins for survival.',
    multipliers: {
      researchCost: 1.7,
      researchTime: 1.55,
      rawSupplyCost: 1.5,
      refinedSupplyCost: 1.58,
      supplierContractCost: 1.55,
      productionOverhead: 1.68,
      employeeLaborCost: 1.42,
      engineerLaborCost: 1.5,
      efficiencyPenalty: 1.85,
      maintenanceBurden: 1.75,
      defectPressure: 1.65,
      rivalResearchSpeed: 1.55,
      rivalMarketPressure: 1.85,
      rivalAggression: 1.72,
    },
  },
  {
    id: 'masochist',
    name: 'Masochist',
    rivalCompanyCount: 7,
    description: 'A brutal pressure-cooker mode intended for players who want every system working against them.',
    multipliers: {
      researchCost: 2.1,
      researchTime: 1.9,
      rawSupplyCost: 1.85,
      refinedSupplyCost: 1.95,
      supplierContractCost: 1.9,
      productionOverhead: 2.05,
      employeeLaborCost: 1.7,
      engineerLaborCost: 1.82,
      efficiencyPenalty: 2.35,
      maintenanceBurden: 2.2,
      defectPressure: 2.05,
      rivalResearchSpeed: 1.9,
      rivalMarketPressure: 2.3,
      rivalAggression: 2.15,
    },
  },
];

export function getDifficultyProfile(difficultyId = 'normal') {
  return difficultyProfiles.find((profile) => profile.id === difficultyId) ?? difficultyProfiles.find((profile) => profile.id === 'normal');
}

export function scaleByDifficulty(value, difficultyId, multiplierKey) {
  const profile = getDifficultyProfile(difficultyId);
  return Math.round(value * (profile.multipliers[multiplierKey] ?? 1));
}

export function rivalCountForDifficulty(difficultyId = 'normal') {
  return getDifficultyProfile(difficultyId).rivalCompanyCount;
}
