export const initialGameState = {
  company: {
    name: 'Orbital Works',
    cash: 12400000,
    reputation: 42,
    cycle: 7,
    burnRate: 420000,
    factoryCapacity: 6,
    warehouseCapacity: 100,
    status: 'operating',
  },
  inventory: {
    rawOre: 42,
    volatiles: 18,
    electronics: 14,
    hullPlate: 22,
    driveCores: 4,
  },
  designs: [
    {
      id: 'cmp-power-bus-a',
      name: 'PB-A Industrial Power Bus',
      type: 'component',
      quality: 56,
      reliability: 72,
      cost: 180000,
      salePrice: 340000,
      licensePrice: 1200000,
      bill: { electronics: 2, hullPlate: 1 },
      rights: 'owned',
      marketListed: false,
    },
    {
      id: 'mod-cargo-spine-a',
      name: 'CS-A Modular Cargo Spine',
      type: 'module',
      quality: 61,
      reliability: 68,
      cost: 420000,
      salePrice: 760000,
      licensePrice: 2200000,
      bill: { rawOre: 3, hullPlate: 3, electronics: 1 },
      rights: 'owned',
      marketListed: false,
    },
    {
      id: 'vsl-yard-hauler-a',
      name: 'YH-A Yard Hauler Hull',
      type: 'vessel',
      quality: 58,
      reliability: 65,
      cost: 1400000,
      salePrice: 2600000,
      licensePrice: 6200000,
      bill: { rawOre: 8, volatiles: 2, electronics: 4, hullPlate: 8, driveCores: 1 },
      rights: 'owned',
      marketListed: false,
    },
  ],
  contracts: [
    {
      id: 'ct-001',
      client: 'Helios Freight Combine',
      title: 'Cargo spine replacement batch',
      category: 'module order',
      requiredType: 'module',
      quantity: 2,
      deadline: 10,
      reward: 2100000,
      penalty: 450000,
      status: 'open',
      assignedDesignId: null,
    },
    {
      id: 'ct-002',
      client: 'Asterion Survey Bureau',
      title: 'Low-cost yard vessel tender',
      category: 'full vessel build',
      requiredType: 'vessel',
      quantity: 1,
      deadline: 12,
      reward: 3900000,
      penalty: 900000,
      status: 'open',
      assignedDesignId: null,
    },
    {
      id: 'ct-003',
      client: 'Keller-Dunn Shipyards',
      title: 'Power bus subcontract',
      category: 'component order',
      requiredType: 'component',
      quantity: 4,
      deadline: 11,
      reward: 1800000,
      penalty: 300000,
      status: 'open',
      assignedDesignId: null,
    },
  ],
  productionRuns: [],
  marketListings: [
    {
      id: 'mk-rival-001',
      seller: 'Tannhauser Drive Systems',
      designName: 'TD-4 Compact Drive Governor',
      type: 'component',
      price: 980000,
      license: true,
    },
    {
      id: 'mk-rival-002',
      seller: 'Vega Hullworks',
      designName: 'VH-2 Pressure Frame',
      type: 'module',
      price: 2100000,
      license: true,
    },
  ],
  research: [
    {
      id: 'rd-supply-1',
      name: 'Bulk Procurement Algorithms',
      discipline: 'supply chain',
      progress: 62,
      required: 100,
      engineers: 2,
      effect: 'Lower procurement costs by 6%',
      status: 'active',
    },
    {
      id: 'rd-prod-1',
      name: 'Factory QA Telemetry',
      discipline: 'manufacturing',
      progress: 28,
      required: 100,
      engineers: 1,
      effect: 'Reduce defect risk in production runs',
      status: 'active',
    },
  ],
  eventLog: [
    'Cycle 007: Prototype management shell online.',
    'Cycle 007: Contract board synced with regional clients.',
  ],
};
