export const initialGameState = {
  company: {
    name: 'Orbital Works',
    cash: 12400000,
    reputation: 42,
    cycle: 7,
    burnRate: 420000,
    factoryCapacity: 6,
    refineryCapacity: 4,
    warehouseCapacity: 100,
    status: 'operating',
    unlockedTechIds: ['tech-scrap-industrial-basics'],
    unlockedNodeIds: [
      'node-crude-power-bus',
      'node-slagged-heat-sink',
      'node-jury-rigged-control-loop',
      'node-riveted-frame-joint',
      'node-chemical-thruster-cluster',
    ],
  },
  inventory: {
    rawOre: 42,
    volatiles: 18,
    electronics: 14,
    hullPlate: 22,
    driveCores: 4,
  },
  commodities: {
    rawOre: { label: 'Raw Ore', spotPrice: 42000, volatility: 0.12, trend: 'stable' },
    volatiles: { label: 'Cryogenic Volatiles', spotPrice: 68000, volatility: 0.16, trend: 'tight' },
    electronics: { label: 'Salvaged Electronics', spotPrice: 92000, volatility: 0.22, trend: 'volatile' },
    hullPlate: { label: 'Hull Plate', spotPrice: 76000, volatility: 0.10, trend: 'stable' },
    driveCores: { label: 'Drive Cores', spotPrice: 310000, volatility: 0.26, trend: 'scarce' },
  },
  supplyContracts: [
    {
      id: 'sup-asteroid-raw-ore',
      supplier: 'Vesta Belt Miners',
      material: 'rawOre',
      quantityPerCycle: 5,
      contractPrice: 36000,
      reliability: 88,
      active: true,
      lockedCycles: 3,
      remainingCycles: 3,
    },
    {
      id: 'sup-gas-volatiles',
      supplier: 'Blue Jovian Tankers',
      material: 'volatiles',
      quantityPerCycle: 2,
      contractPrice: 59000,
      reliability: 76,
      active: true,
      lockedCycles: 3,
      remainingCycles: 3,
    },
    {
      id: 'sup-scrap-electronics',
      supplier: 'Kepler Salvage Exchange',
      material: 'electronics',
      quantityPerCycle: 3,
      contractPrice: 84000,
      reliability: 64,
      active: false,
      lockedCycles: 4,
      remainingCycles: 0,
    },
    {
      id: 'sup-forge-hullplate',
      supplier: 'Redline Forge Compact',
      material: 'hullPlate',
      quantityPerCycle: 4,
      contractPrice: 70000,
      reliability: 82,
      active: false,
      lockedCycles: 4,
      remainingCycles: 0,
    },
    {
      id: 'sup-core-drivecores',
      supplier: 'Axiom Drive Brokerage',
      material: 'driveCores',
      quantityPerCycle: 1,
      contractPrice: 285000,
      reliability: 58,
      active: false,
      lockedCycles: 5,
      remainingCycles: 0,
    },
  ],
  refineryJobs: [],
  engineers: [
    {
      id: 'eng-mara-kade',
      name: 'Mara Kade',
      specialty: 'supply chain',
      skill: 3,
      salary: 92000,
      fatigue: 8,
      morale: 78,
      assignedProjectId: 'rd-supply-1',
    },
    {
      id: 'eng-silas-orr',
      name: 'Silas Orr',
      specialty: 'manufacturing',
      skill: 2,
      salary: 81000,
      fatigue: 14,
      morale: 72,
      assignedProjectId: 'rd-prod-1',
    },
    {
      id: 'eng-nyx-valen',
      name: 'Nyx Valen',
      specialty: 'propulsion',
      skill: 2,
      salary: 84000,
      fatigue: 5,
      morale: 81,
      assignedProjectId: null,
    },
    {
      id: 'eng-iona-brigg',
      name: 'Iona Brigg',
      specialty: 'materials',
      skill: 1,
      salary: 68000,
      fatigue: 0,
      morale: 88,
      assignedProjectId: null,
    },
  ],
  finishedGoods: [],
  designs: [
    {
      id: 'cmp-power-bus-a',
      name: 'PB-A Industrial Power Bus',
      type: 'component',
      quality: 56,
      reliability: 72,
      cost: 180000,
      salePrice: 340000,
      licensePrice: 1200000,
      bill: { electronics: 2, hullPlate: 1 },
      rights: 'owned',
      marketListed: false,
    },
    {
      id: 'mod-cargo-spine-a',
      name: 'CS-A Modular Cargo Spine',
      type: 'module',
      quality: 61,
      reliability: 68,
      cost: 420000,
      salePrice: 760000,
      licensePrice: 2200000,
      bill: { rawOre: 3, hullPlate: 3, electronics: 1 },
      rights: 'owned',
      marketListed: false,
    },
    {
      id: 'vsl-yard-hauler-a',
      name: 'YH-A Yard Hauler Hull',
      type: 'vessel',
      quality: 58,
      reliability: 65,
      cost: 1400000,
      salePrice: 2600000,
      licensePrice: 6200000,
      bill: { rawOre: 8, volatiles: 2, electronics: 4, hullPlate: 8, driveCores: 1 },
      rights: 'owned',
      marketListed: false,
    },
  ],
  contracts: [
    {
      id: 'ct-001',
      client: 'Helios Freight Combine',
      title: 'Cargo spine replacement batch',
      category: 'module order',
      requiredType: 'module',
      quantity: 2,
      deadline: 10,
      reward: 2100000,
      penalty: 450000,
      status: 'open',
      assignedDesignId: null,
      productionRunId: null,
      stockLotId: null,
      deliveredQuantity: 0,
      earnedReward: 0,
    },
    {
      id: 'ct-002',
      client: 'Asterion Survey Bureau',
      title: 'Low-cost yard vessel tender',
      category: 'full vessel build',
      requiredType: 'vessel',
      quantity: 1,
      deadline: 12,
      reward: 3900000,
      penalty: 900000,
      status: 'open',
      assignedDesignId: null,
      productionRunId: null,
      stockLotId: null,
      deliveredQuantity: 0,
      earnedReward: 0,
    },
    {
      id: 'ct-003',
      client: 'Keller-Dunn Shipyards',
      title: 'Power bus subcontract',
      category: 'component order',
      requiredType: 'component',
      quantity: 4,
      deadline: 11,
      reward: 1800000,
      penalty: 300000,
      status: 'open',
      assignedDesignId: null,
      productionRunId: null,
      stockLotId: null,
      deliveredQuantity: 0,
      earnedReward: 0,
    },
  ],
  productionRuns: [],
  marketListings: [
    {
      id: 'mk-rival-001',
      seller: 'Tannhauser Drive Systems',
      designName: 'TD-4 Compact Drive Governor',
      type: 'component',
      price: 980000,
      license: true,
    },
    {
      id: 'mk-rival-002',
      seller: 'Vega Hullworks',
      designName: 'VH-2 Pressure Frame',
      type: 'module',
      price: 2100000,
      license: true,
    },
  ],
  research: [
    {
      id: 'rd-supply-1',
      name: 'Bulk Procurement Algorithms',
      discipline: 'supply chain',
      progress: 62,
      required: 100,
      effect: 'Lower procurement costs by 6%',
      status: 'active',
      stalled: false,
    },
    {
      id: 'rd-prod-1',
      name: 'Factory QA Telemetry',
      discipline: 'manufacturing',
      progress: 28,
      required: 100,
      effect: 'Reduce defect risk in production runs',
      status: 'active',
      stalled: false,
    },
    {
      id: 'rd-mat-1',
      name: 'Composite Hull Alloys',
      discipline: 'materials',
      progress: 0,
      required: 120,
      effect: 'Unlock stronger early hull patterns and lattice fabrication nodes',
      unlockTechId: 'tech-structural-lattice',
      status: 'active',
      stalled: true,
    },
    {
      id: 'rd-power-1',
      name: 'Baseline Power Handling',
      discipline: 'reactor',
      progress: 0,
      required: 80,
      effect: 'Unlock capacitor banks and stable early power routing',
      unlockTechId: 'tech-baseline-power-handling',
      status: 'active',
      stalled: true,
    },
    {
      id: 'rd-control-1',
      name: 'Fault-Tolerant Control Logic',
      discipline: 'manufacturing',
      progress: 0,
      required: 110,
      effect: 'Unlock redundant control cores for lower defect escape',
      unlockTechId: 'tech-fault-tolerant-controls',
      status: 'active',
      stalled: true,
    },
    {
      id: 'rd-thermal-1',
      name: 'Precision Thermal Paths',
      discipline: 'materials',
      progress: 0,
      required: 135,
      effect: 'Unlock microchannel cooling and compact thermal control',
      unlockTechId: 'tech-precision-thermal',
      status: 'active',
      stalled: true,
    },
    {
      id: 'rd-reactor-1',
      name: 'Hazardous Reactor Access',
      discipline: 'reactor',
      progress: 0,
      required: 95,
      effect: 'Unlock primitive reactor taps with high power and high risk',
      unlockTechId: 'tech-hazardous-reactor-access',
      status: 'active',
      stalled: true,
    },
    {
      id: 'rd-reactor-2',
      name: 'Compact Reactor Spines',
      discipline: 'reactor',
      progress: 0,
      required: 180,
      effect: 'Unlock compact reactor spines for late high-output power systems',
      unlockTechId: 'tech-compact-reactor-spines',
      status: 'active',
      stalled: true,
    },
    {
      id: 'rd-propulsion-1',
      name: 'Vector Plasma Propulsion',
      discipline: 'propulsion',
      progress: 0,
      required: 170,
      effect: 'Unlock vector plasma drives for compact high-thrust modules',
      unlockTechId: 'tech-vector-plasma-propulsion',
      status: 'active',
      stalled: true,
    },
  ],
  eventLog: [
    'Cycle 007: Prototype management shell online.',
    'Cycle 007: Contract board synced with regional clients.',
  ],
};
