export const componentNodeLibrary = [
  {
    id: 'node-crude-power-bus',
    name: 'Crude Power Bus',
    family: 'power distribution',
    tier: 0,
    researchLevel: 'pre-standard industrial',
    description: 'An oversized, poorly shielded power trunk assembled from crude bus bars and salvage-grade regulators. It works, but every module chained through it inherits heat, instability, and maintenance problems.',
    affects: ['module power draw', 'heat', 'failure rate', 'maintenance burden'],
    stats: { powerDraw: 12, heat: 10, reliability: -18, defectRisk: 16, maintenance: 22, cost: -8, mass: 12 },
    ports: { inputs: 1, outputs: 2 },
    shape: ['XX', 'X.'],
    tags: ['early', 'crude', 'cheap', 'unstable'],
  },
  {
    id: 'node-basic-capacitor-bank',
    name: 'Basic Capacitor Bank',
    family: 'power distribution',
    tier: 1,
    researchLevel: 'baseline industrial',
    description: 'A simple capacitor buffer that smooths brief load spikes. It slightly improves reliability when placed between reactors and hungry subsystems, but adds mass and heat concentration.',
    affects: ['power stability', 'reliability', 'heat', 'mass'],
    stats: { powerStability: 8, reliability: 6, heat: 4, mass: 8, cost: 6 },
    ports: { inputs: 1, outputs: 2 },
    shape: ['XX'],
    tags: ['buffer', 'baseline'],
  },
  {
    id: 'node-primitive-reactor-tap',
    name: 'Primitive Reactor Tap',
    family: 'reactor',
    tier: 0,
    researchLevel: 'hazardous prototype',
    description: 'A rough reactor extraction tap with poor isolation. It provides serious output for early designs, but generates extreme heat and regular fault events.',
    affects: ['power output', 'heat', 'failure rate', 'crew risk'],
    stats: { powerOutput: 34, heat: 28, reliability: -24, defectRisk: 18, maintenance: 26, crewRisk: 16, mass: 18 },
    ports: { inputs: 0, outputs: 3 },
    shape: ['XX', 'XX'],
    tags: ['reactor', 'dangerous', 'early'],
  },
  {
    id: 'node-compact-reactor-spine',
    name: 'Compact Reactor Spine',
    family: 'reactor',
    tier: 4,
    researchLevel: 'advanced compact power',
    description: 'A mature high-output reactor spine that shrinks power generation while improving stability. Unlike most late-game performance nodes, it improves output and efficiency at the same time.',
    affects: ['power output', 'mass', 'reliability', 'efficiency'],
    stats: { powerOutput: 86, efficiency: 32, reliability: 22, heat: 12, mass: -18, maintenance: -10, cost: 42 },
    ports: { inputs: 0, outputs: 4 },
    shape: ['XXX', '.X.'],
    tags: ['reactor', 'late', 'efficient', 'compact'],
  },
  {
    id: 'node-slagged-heat-sink',
    name: 'Slagged Heat Sink',
    family: 'thermal',
    tier: 0,
    researchLevel: 'scrap thermal control',
    description: 'A crude block of thermal mass and welded fins. It reduces immediate overheating but makes the module heavy and slow to service.',
    affects: ['heat', 'mass', 'maintenance burden'],
    stats: { heat: -14, mass: 18, maintenance: 10, reliability: -4, cost: -4 },
    ports: { inputs: 1, outputs: 1 },
    shape: ['X', 'X'],
    tags: ['thermal', 'crude', 'heavy'],
  },
  {
    id: 'node-microchannel-cooler',
    name: 'Microchannel Cooler',
    family: 'thermal',
    tier: 3,
    researchLevel: 'precision thermal control',
    description: 'A compact precision cooling path that removes heat efficiently, but can be fragile if installed beside high-vibration machinery.',
    affects: ['heat', 'efficiency', 'reliability', 'defect risk'],
    stats: { heat: -30, efficiency: 12, mass: -6, defectRisk: 4, maintenance: 2, cost: 22 },
    ports: { inputs: 2, outputs: 2 },
    shape: ['XX', '.X'],
    tags: ['thermal', 'compact', 'precision'],
  },
  {
    id: 'node-jury-rigged-control-loop',
    name: 'Jury-Rigged Control Loop',
    family: 'control systems',
    tier: 0,
    researchLevel: 'improvised control logic',
    description: 'A messy control chain of relays, salvage processors, and emergency overrides. It enables automation, but the error profile is ugly.',
    affects: ['automation', 'defect risk', 'failure rate', 'maintenance burden'],
    stats: { automation: 10, defectRisk: 20, reliability: -20, maintenance: 18, cost: -10 },
    ports: { inputs: 2, outputs: 2 },
    shape: ['X.', 'XX'],
    tags: ['control', 'early', 'unreliable'],
  },
  {
    id: 'node-redundant-control-core',
    name: 'Redundant Control Core',
    family: 'control systems',
    tier: 2,
    researchLevel: 'fault-tolerant automation',
    description: 'A control core with backup paths and better diagnostics. It reduces defect escape and improves reliability, at the cost of electronics demand.',
    affects: ['automation', 'reliability', 'defect risk', 'electronics cost'],
    stats: { automation: 18, reliability: 18, defectRisk: -12, maintenance: -8, cost: 18, electronicsDemand: 8 },
    ports: { inputs: 2, outputs: 3 },
    shape: ['XX', 'XX'],
    tags: ['control', 'reliable'],
  },
  {
    id: 'node-riveted-frame-joint',
    name: 'Riveted Frame Joint',
    family: 'structure',
    tier: 0,
    researchLevel: 'crude structural fabrication',
    description: 'A rough frame junction using thick plate and brute-force fastening. It is durable in a primitive way but heavy, imprecise, and labor-intensive.',
    affects: ['durability', 'mass', 'manufacturing time', 'defect risk'],
    stats: { durability: 16, mass: 22, productionTime: 12, defectRisk: 10, cost: -6 },
    ports: { inputs: 1, outputs: 3 },
    shape: ['X', 'X', 'X'],
    tags: ['structure', 'crude', 'heavy'],
  },
  {
    id: 'node-lattice-frame-joint',
    name: 'Lattice Frame Joint',
    family: 'structure',
    tier: 3,
    researchLevel: 'optimized structural lattice',
    description: 'A lighter structural junction that distributes stress through engineered lattice members. It improves durability per unit mass but demands tighter fabrication tolerances.',
    affects: ['durability', 'mass', 'manufacturability', 'defect risk'],
    stats: { durability: 28, mass: -16, efficiency: 10, defectRisk: 4, cost: 24 },
    ports: { inputs: 2, outputs: 4 },
    shape: ['X.X', '.X.'],
    tags: ['structure', 'advanced', 'lightweight'],
  },
  {
    id: 'node-chemical-thruster-cluster',
    name: 'Chemical Thruster Cluster',
    family: 'propulsion',
    tier: 0,
    researchLevel: 'primitive propulsion',
    description: 'A brute-force thruster cluster with bad fuel economy and ugly maintenance needs. It provides movement, barely, and drinks volatiles like a furnace drinks air.',
    affects: ['thrust', 'fuel use', 'maintenance burden', 'heat'],
    stats: { thrust: 24, efficiency: -22, heat: 16, maintenance: 24, reliability: -12, fuelUse: 30 },
    ports: { inputs: 2, outputs: 1 },
    shape: ['XX', 'XX', '.X'],
    tags: ['propulsion', 'early', 'inefficient'],
  },
  {
    id: 'node-vector-plasma-drive',
    name: 'Vector Plasma Drive',
    family: 'propulsion',
    tier: 4,
    researchLevel: 'advanced high-performance propulsion',
    description: 'A fast, precise plasma vectoring system. It is compact and powerful, but the power draw is obscene unless paired with serious reactor technology.',
    affects: ['thrust', 'maneuvering', 'power draw', 'heat'],
    stats: { thrust: 74, maneuvering: 36, mass: -12, powerDraw: 44, heat: 28, cost: 48, maintenance: 6 },
    ports: { inputs: 3, outputs: 1 },
    shape: ['.X.', 'XXX'],
    tags: ['propulsion', 'late', 'power-hungry'],
  },
];

export const technologyTree = [
  {
    id: 'tech-scrap-industrial-basics',
    name: 'Scrap Industrial Basics',
    tier: 0,
    family: 'foundational manufacturing',
    unlocks: ['node-crude-power-bus', 'node-slagged-heat-sink', 'node-jury-rigged-control-loop', 'node-riveted-frame-joint', 'node-chemical-thruster-cluster'],
    description: 'The ugly starting layer: cheap, bulky, failure-prone industrial nodes that make early designs work badly enough to need improvement.',
  },
  {
    id: 'tech-baseline-power-handling',
    name: 'Baseline Power Handling',
    tier: 1,
    family: 'power distribution',
    prerequisites: ['tech-scrap-industrial-basics'],
    unlocks: ['node-basic-capacitor-bank'],
    description: 'Basic stabilization and buffer technology for early modules that cannot yet support elegant power architecture.',
  },
  {
    id: 'tech-hazardous-reactor-access',
    name: 'Hazardous Reactor Access',
    tier: 1,
    family: 'reactor',
    prerequisites: ['tech-scrap-industrial-basics'],
    unlocks: ['node-primitive-reactor-tap'],
    description: 'Dangerous early power extraction. High output, terrible heat profile, ugly risk.',
  },
  {
    id: 'tech-fault-tolerant-controls',
    name: 'Fault-Tolerant Controls',
    tier: 2,
    family: 'control systems',
    prerequisites: ['tech-baseline-power-handling'],
    unlocks: ['node-redundant-control-core'],
    description: 'Better diagnostic and backup-path logic that lowers defect escape and improves maintainability.',
  },
  {
    id: 'tech-precision-thermal',
    name: 'Precision Thermal Paths',
    tier: 3,
    family: 'thermal',
    prerequisites: ['tech-fault-tolerant-controls'],
    unlocks: ['node-microchannel-cooler'],
    description: 'Compact cooling improvements that reduce mass and heat but require tighter fabrication tolerances.',
  },
  {
    id: 'tech-structural-lattice',
    name: 'Structural Lattice Fabrication',
    tier: 3,
    family: 'structure',
    prerequisites: ['tech-fault-tolerant-controls'],
    unlocks: ['node-lattice-frame-joint'],
    description: 'Weight-saving structural nodes that increase durability per mass while raising manufacturing precision demands.',
  },
  {
    id: 'tech-vector-plasma-propulsion',
    name: 'Vector Plasma Propulsion',
    tier: 4,
    family: 'propulsion',
    prerequisites: ['tech-precision-thermal', 'tech-structural-lattice'],
    unlocks: ['node-vector-plasma-drive'],
    description: 'Late high-performance drive systems: fast and compact, but brutal on power and thermal budgets.',
  },
  {
    id: 'tech-compact-reactor-spines',
    name: 'Compact Reactor Spines',
    tier: 4,
    family: 'reactor',
    prerequisites: ['tech-hazardous-reactor-access', 'tech-precision-thermal'],
    unlocks: ['node-compact-reactor-spine'],
    description: 'The reactor exception path: smaller, cleaner, higher-output power generation that makes late power-hungry systems viable.',
  },
];

export const corporationTechnologySeeds = [
  {
    id: 'corp-player-orbital-works',
    name: 'Orbital Works',
    mode: 'player-randomized-campaign-seed',
    marketShare: 0,
    unlockedNodeIds: ['node-crude-power-bus', 'node-slagged-heat-sink', 'node-jury-rigged-control-loop', 'node-riveted-frame-joint'],
    unlockedTechIds: ['tech-scrap-industrial-basics'],
    description: 'A shaky but flexible starter package. The player begins with bad industrial fundamentals and must research toward reliability and performance.',
  },
  {
    id: 'corp-tannhauser-drive-systems',
    name: 'Tannhauser Drive Systems',
    mode: 'campaign-fixed-propulsion-specialist',
    marketShare: 18,
    unlockedNodeIds: ['node-chemical-thruster-cluster', 'node-basic-capacitor-bank', 'node-vector-plasma-drive'],
    unlockedTechIds: ['tech-scrap-industrial-basics', 'tech-baseline-power-handling', 'tech-vector-plasma-propulsion'],
    description: 'A propulsion-heavy NPC corporation with superior drive access but dangerous power demands.',
  },
  {
    id: 'corp-vega-hullworks',
    name: 'Vega Hullworks',
    mode: 'campaign-fixed-structure-specialist',
    marketShare: 14,
    unlockedNodeIds: ['node-riveted-frame-joint', 'node-lattice-frame-joint', 'node-slagged-heat-sink'],
    unlockedTechIds: ['tech-scrap-industrial-basics', 'tech-structural-lattice'],
    description: 'A hull and structure specialist with better frame nodes and more efficient mass distribution.',
  },
  {
    id: 'corp-axiom-reactor-brokerage',
    name: 'Axiom Reactor Brokerage',
    mode: 'campaign-fixed-reactor-specialist',
    marketShare: 11,
    unlockedNodeIds: ['node-primitive-reactor-tap', 'node-compact-reactor-spine', 'node-basic-capacitor-bank'],
    unlockedTechIds: ['tech-hazardous-reactor-access', 'tech-compact-reactor-spines'],
    description: 'A power-system specialist with reactor access that can eventually support extreme late-game power demand.',
  },
];

export function nodesForCorporation(corporation) {
  const ids = new Set(corporation.unlockedNodeIds ?? []);
  return componentNodeLibrary.filter((node) => ids.has(node.id));
}

export function summarizeNodeStats(nodes) {
  return nodes.reduce((summary, node) => {
    for (const [stat, value] of Object.entries(node.stats ?? {})) {
      summary[stat] = (summary[stat] ?? 0) + value;
    }
    return summary;
  }, {});
}
