export const expandedComponentNodes = [
  {
    id: 'node-scrap-relay-matrix',
    name: 'Scrap Relay Matrix',
    family: 'control systems',
    tier: 0,
    researchLevel: 'scrap logic handling',
    description: 'A crude relay panel that adds cheap control capacity but amplifies noisy upstream power and raises defect escape.',
    affects: ['automation', 'defect risk', 'cost'],
    stats: { automation: 7, defectRisk: 12, reliability: -10, maintenance: 10, cost: -6 },
    ports: { inputs: 2, outputs: 3 },
    shape: ['XX'],
    tags: ['control', 'early', 'crude', 'cheap', 'unstable'],
  },
  {
    id: 'node-welded-service-frame',
    name: 'Welded Service Frame',
    family: 'structure',
    tier: 0,
    researchLevel: 'scrap service fabrication',
    description: 'A low-grade service frame that makes parts easier to bolt together but leaves ugly vibration and alignment tolerances.',
    affects: ['durability', 'maintenance', 'defect risk'],
    stats: { durability: 10, mass: 14, maintenance: 6, defectRisk: 7, cost: -5 },
    ports: { inputs: 2, outputs: 2 },
    shape: ['XX', '..', 'XX'],
    tags: ['structure', 'early', 'crude', 'serviceable'],
  },
  {
    id: 'node-charred-radiator-fin',
    name: 'Charred Radiator Fin',
    family: 'thermal',
    tier: 0,
    researchLevel: 'scrap heat rejection',
    description: 'A scavenged fin stack that vents heat cheaply but cracks under high vibration and needs frequent patching.',
    affects: ['heat', 'maintenance', 'reliability'],
    stats: { heat: -9, mass: 9, maintenance: 12, reliability: -6, cost: -7 },
    ports: { inputs: 1, outputs: 2 },
    shape: ['X.', 'XX'],
    tags: ['thermal', 'early', 'crude', 'cheap'],
  },
  {
    id: 'node-stable-inverter-bridge',
    name: 'Stable Inverter Bridge',
    family: 'power distribution',
    tier: 1,
    researchLevel: 'baseline power conversion',
    description: 'A sturdier inverter bridge that converts ugly generation into usable subsystem power, improving chain stability at added electronics cost.',
    affects: ['power stability', 'efficiency', 'electronics cost'],
    stats: { powerStability: 14, reliability: 8, efficiency: 5, heat: 3, cost: 12, electronicsDemand: 5 },
    ports: { inputs: 2, outputs: 3 },
    shape: ['XXX'],
    tags: ['power', 'baseline', 'buffer'],
  },
  {
    id: 'node-line-noise-filter',
    name: 'Line Noise Filter',
    family: 'power distribution',
    tier: 1,
    researchLevel: 'baseline signal protection',
    description: 'A modest filter assembly that protects downstream control and sensor hardware from power ripple.',
    affects: ['reliability', 'defect risk', 'power stability'],
    stats: { powerStability: 7, reliability: 7, defectRisk: -5, maintenance: 1, cost: 9 },
    ports: { inputs: 1, outputs: 2 },
    shape: ['X'],
    tags: ['power', 'baseline', 'filter'],
  },
  {
    id: 'node-serviceable-fuel-pump',
    name: 'Serviceable Fuel Pump',
    family: 'propulsion',
    tier: 1,
    researchLevel: 'baseline propellant handling',
    description: 'A maintainable fuel pump that improves early thrust reliability without becoming a high-performance drive system.',
    affects: ['thrust', 'fuel use', 'maintenance'],
    stats: { thrust: 16, efficiency: 4, fuelUse: 10, reliability: 5, maintenance: -3, cost: 10 },
    ports: { inputs: 2, outputs: 1 },
    shape: ['XX'],
    tags: ['propulsion', 'baseline', 'serviceable'],
  },
  {
    id: 'node-diagnostic-watchdog-core',
    name: 'Diagnostic Watchdog Core',
    family: 'control systems',
    tier: 2,
    researchLevel: 'diagnostic automation',
    description: 'A diagnostic controller that catches drift and intermittent defects before they escape into production runs.',
    affects: ['defect risk', 'reliability', 'automation'],
    stats: { automation: 12, reliability: 14, defectRisk: -15, maintenance: -5, electronicsDemand: 6, cost: 16 },
    ports: { inputs: 2, outputs: 2 },
    shape: ['.X.', 'XXX'],
    tags: ['control', 'diagnostic', 'reliable'],
  },
  {
    id: 'node-sealed-logic-bus',
    name: 'Sealed Logic Bus',
    family: 'control systems',
    tier: 2,
    researchLevel: 'sealed industrial automation',
    description: 'A sealed logic spine that resists contamination and vibration, but is harder to service after installation.',
    affects: ['automation', 'reliability', 'maintenance'],
    stats: { automation: 16, reliability: 12, defectRisk: -8, maintenance: 5, cost: 18 },
    ports: { inputs: 3, outputs: 3 },
    shape: ['XXX', '.X.'],
    tags: ['control', 'sealed', 'reliable'],
  },
  {
    id: 'node-floating-isolation-mount',
    name: 'Floating Isolation Mount',
    family: 'structure',
    tier: 2,
    researchLevel: 'vibration isolation',
    description: 'A vibration-isolated mount that protects precision nodes and drive hardware, adding cost and some mass.',
    affects: ['reliability', 'defect risk', 'mass'],
    stats: { durability: 12, reliability: 10, defectRisk: -8, mass: 6, cost: 14 },
    ports: { inputs: 2, outputs: 3 },
    shape: ['X.X', 'XXX'],
    tags: ['structure', 'isolation', 'precision-support'],
  },
  {
    id: 'node-recirculating-coolant-loop',
    name: 'Recirculating Coolant Loop',
    family: 'thermal',
    tier: 2,
    researchLevel: 'controlled coolant management',
    description: 'A pump-driven coolant loop that offers better active heat control than a passive sink, but depends on control supervision.',
    affects: ['heat', 'maintenance', 'efficiency'],
    stats: { heat: -20, efficiency: 5, maintenance: 4, reliability: 4, cost: 16 },
    ports: { inputs: 2, outputs: 3 },
    shape: ['XX', 'XX'],
    tags: ['thermal', 'active', 'coolant'],
  },
  {
    id: 'node-ceramic-heat-exchanger',
    name: 'Ceramic Heat Exchanger',
    family: 'thermal',
    tier: 3,
    researchLevel: 'precision heat exchange',
    description: 'A compact ceramic exchanger with excellent heat handling but poor tolerance for crude upstream contamination.',
    affects: ['heat', 'mass', 'defect risk'],
    stats: { heat: -24, efficiency: 8, mass: -4, defectRisk: 3, cost: 24 },
    ports: { inputs: 2, outputs: 2 },
    shape: ['.X', 'XX'],
    tags: ['thermal', 'precision', 'compact'],
  },
  {
    id: 'node-composite-load-web',
    name: 'Composite Load Web',
    family: 'structure',
    tier: 3,
    researchLevel: 'composite load transfer',
    description: 'A composite web that spreads load through lighter paths, excellent for compact systems but sensitive to fabrication quality.',
    affects: ['durability', 'mass', 'efficiency'],
    stats: { durability: 22, mass: -12, efficiency: 8, defectRisk: 3, cost: 24 },
    ports: { inputs: 3, outputs: 4 },
    shape: ['X.X', '.X.', 'X.X'],
    tags: ['structure', 'advanced', 'lightweight', 'precision'],
  },
  {
    id: 'node-pulsed-plasma-injector',
    name: 'Pulsed Plasma Injector',
    family: 'propulsion',
    tier: 3,
    researchLevel: 'high-energy propellant injection',
    description: 'A pulsed injector that increases drive response and thrust density, but creates hard power and thermal spikes.',
    affects: ['thrust', 'maneuvering', 'power draw', 'heat'],
    stats: { thrust: 38, maneuvering: 16, powerDraw: 24, heat: 16, maintenance: 5, cost: 28 },
    ports: { inputs: 3, outputs: 1 },
    shape: ['XXX', '..X'],
    tags: ['propulsion', 'precision', 'power-hungry'],
  },
  {
    id: 'node-capillary-reactor-limiter',
    name: 'Capillary Reactor Limiter',
    family: 'reactor',
    tier: 3,
    researchLevel: 'reactor output limiting',
    description: 'A regulating limiter that lowers reactor spike behavior, sacrificing some output for major reliability improvement.',
    affects: ['power output', 'reliability', 'heat'],
    stats: { powerOutput: 28, powerStability: 18, reliability: 18, heat: 5, maintenance: -5, cost: 28 },
    ports: { inputs: 1, outputs: 3 },
    shape: ['XX', '.X'],
    tags: ['reactor', 'regulator', 'reliable'],
  },
  {
    id: 'node-superconducting-bus-spine',
    name: 'Superconducting Bus Spine',
    family: 'power distribution',
    tier: 4,
    researchLevel: 'advanced compact power transfer',
    description: 'A compact high-end power spine with very low losses, demanding serious thermal discipline and precision manufacturing.',
    affects: ['power stability', 'efficiency', 'mass', 'cost'],
    stats: { powerStability: 26, efficiency: 22, reliability: 12, heat: -4, mass: -8, cost: 42, electronicsDemand: 10 },
    ports: { inputs: 3, outputs: 4 },
    shape: ['XXXX'],
    tags: ['power', 'late', 'compact', 'precision'],
  },
  {
    id: 'node-predictive-control-mesh',
    name: 'Predictive Control Mesh',
    family: 'control systems',
    tier: 4,
    researchLevel: 'predictive automation',
    description: 'A predictive control mesh that forecasts load, heat, and fault states, greatly improving advanced component behavior at high electronics cost.',
    affects: ['automation', 'reliability', 'defect risk', 'electronics cost'],
    stats: { automation: 30, reliability: 20, defectRisk: -20, efficiency: 8, electronicsDemand: 14, cost: 36 },
    ports: { inputs: 4, outputs: 4 },
    shape: ['XXX', 'X.X'],
    tags: ['control', 'late', 'reliable', 'precision'],
  },
  {
    id: 'node-closed-cycle-thermal-stack',
    name: 'Closed-Cycle Thermal Stack',
    family: 'thermal',
    tier: 4,
    researchLevel: 'advanced thermal recovery',
    description: 'A closed-cycle thermal stack that turns waste heat management into a performance stabilizer, but adds expensive service complexity.',
    affects: ['heat', 'efficiency', 'reliability', 'maintenance'],
    stats: { heat: -38, efficiency: 16, reliability: 12, maintenance: 8, cost: 38 },
    ports: { inputs: 3, outputs: 3 },
    shape: ['.XX', 'XX.'],
    tags: ['thermal', 'late', 'compact', 'precision'],
  },
  {
    id: 'node-field-collimated-drive-ring',
    name: 'Field-Collimated Drive Ring',
    family: 'propulsion',
    tier: 4,
    researchLevel: 'field-collimated propulsion',
    description: 'A precise drive ring that converts advanced power into dense thrust and maneuvering authority, but punishes weak power architecture.',
    affects: ['thrust', 'maneuvering', 'power draw', 'heat'],
    stats: { thrust: 68, maneuvering: 30, powerDraw: 36, heat: 18, mass: -8, cost: 44, maintenance: 8 },
    ports: { inputs: 4, outputs: 1 },
    shape: ['.X.', 'XXX', '.X.'],
    tags: ['propulsion', 'late', 'power-hungry', 'precision'],
  },
];

export const expandedTechnologyUnlocks = {
  'tech-scrap-industrial-basics': ['node-scrap-relay-matrix', 'node-welded-service-frame', 'node-charred-radiator-fin'],
  'tech-baseline-power-handling': ['node-stable-inverter-bridge', 'node-line-noise-filter', 'node-serviceable-fuel-pump'],
  'tech-fault-tolerant-controls': ['node-diagnostic-watchdog-core', 'node-sealed-logic-bus', 'node-floating-isolation-mount', 'node-recirculating-coolant-loop'],
  'tech-precision-thermal': ['node-ceramic-heat-exchanger', 'node-capillary-reactor-limiter'],
  'tech-structural-lattice': ['node-composite-load-web'],
  'tech-vector-plasma-propulsion': ['node-pulsed-plasma-injector', 'node-field-collimated-drive-ring'],
  'tech-compact-reactor-spines': ['node-superconducting-bus-spine', 'node-predictive-control-mesh', 'node-closed-cycle-thermal-stack'],
};
