import { rivalCountForDifficulty } from './difficultyProfiles.js';

export const rivalCompanyTemplates = [
  {
    id: 'rival-ironwake',
    name: 'Ironwake Heavy Systems',
    archetype: 'heavy industrial reliability competitor',
    advantages: ['high structure reliability', 'cheap hull reinforcement', 'strong supplier discipline'],
    disadvantages: ['slow research', 'poor luxury market appeal'],
    preferredModuleCategories: ['structure', 'power', 'cargo'],
    preferredVehicleClasses: ['utility hauler', 'industrial tug', 'yard vessel'],
    researchPreferences: ['structure', 'power', 'manufacturing'],
    competitiveBehavior: 'Undercuts fragile competitors with durable, heavy, low-glamour workhorse designs.',
    pricingStrategy: 'value-durable',
    licensingStrategy: 'rarely licenses core hull technology',
    aggressionIndex: 0.62,
    contractBidAggression: 0.72,
    marketShareBias: 0.08,
    techLevelBehaviors: [
      { minTechLevel: 1, behavior: 'Focuses on cheap rugged frames and low-bid industrial contracts.' },
      { minTechLevel: 4, behavior: 'Begins bundling reinforced hull kits with maintenance contracts.' },
      { minTechLevel: 7, behavior: 'Competes aggressively in high-mass commercial vehicle markets.' },
    ],
  },
  {
    id: 'rival-silverline',
    name: 'Silverline Executive Aerospace',
    archetype: 'premium high-margin designer',
    advantages: ['high sale price tolerance', 'premium brand reputation', 'strong control systems'],
    disadvantages: ['expensive production', 'weak low-bid contract behavior'],
    preferredModuleCategories: ['control', 'utility', 'thermal'],
    preferredVehicleClasses: ['executive courier', 'survey craft', 'premium utility vessel'],
    researchPreferences: ['control', 'automation', 'comfort systems'],
    competitiveBehavior: 'Avoids price wars and chases premium high-reputation contracts.',
    pricingStrategy: 'premium-margin',
    licensingStrategy: 'licenses older premium modules at high royalty rates',
    aggressionIndex: 0.45,
    contractBidAggression: 0.38,
    marketShareBias: 0.05,
    techLevelBehaviors: [
      { minTechLevel: 1, behavior: 'Markets expensive but comfortable control-heavy vessels.' },
      { minTechLevel: 5, behavior: 'Leans into automation and premium service packages.' },
      { minTechLevel: 8, behavior: 'Dominates high-end specialized craft if left alone.' },
    ],
  },
  {
    id: 'rival-redline',
    name: 'Redline Thrust Concern',
    archetype: 'propulsion-first speed competitor',
    advantages: ['fast propulsion research', 'strong thrust performance', 'aggressive marketing'],
    disadvantages: ['heat issues', 'higher defect pressure'],
    preferredModuleCategories: ['propulsion', 'power', 'thermal'],
    preferredVehicleClasses: ['runner', 'interceptor', 'fast courier'],
    researchPreferences: ['propulsion', 'thermal', 'power'],
    competitiveBehavior: 'Floods speed-sensitive markets with hot, fast, dramatic designs.',
    pricingStrategy: 'performance-markup',
    licensingStrategy: 'licenses propulsion packages aggressively',
    aggressionIndex: 0.84,
    contractBidAggression: 0.7,
    marketShareBias: 0.07,
    techLevelBehaviors: [
      { minTechLevel: 1, behavior: 'Overpowers early designs and accepts maintenance complaints.' },
      { minTechLevel: 4, behavior: 'Pairs drives with thermal kits to reduce failure reputation.' },
      { minTechLevel: 7, behavior: 'Attempts to dominate fast transport and military-adjacent contracts.' },
    ],
  },
  {
    id: 'rival-greenhold',
    name: 'Greenhold Sustainable Drives',
    archetype: 'efficiency and low-overhead competitor',
    advantages: ['low power draw', 'lower heat', 'supplier efficiency'],
    disadvantages: ['lower peak thrust', 'slow military adoption'],
    preferredModuleCategories: ['power', 'thermal', 'utility'],
    preferredVehicleClasses: ['long-haul utility', 'survey vessel', 'civilian transport'],
    researchPreferences: ['efficiency', 'thermal', 'reactor miniaturization'],
    competitiveBehavior: 'Wins long-run operating-cost comparisons and civilian procurement cycles.',
    pricingStrategy: 'lifecycle-savings',
    licensingStrategy: 'licenses efficiency modules widely',
    aggressionIndex: 0.52,
    contractBidAggression: 0.5,
    marketShareBias: 0.06,
    techLevelBehaviors: [
      { minTechLevel: 1, behavior: 'Competes on lower operating costs rather than sticker price.' },
      { minTechLevel: 5, behavior: 'Begins marketing lifetime maintenance savings.' },
      { minTechLevel: 8, behavior: 'Becomes dangerous in markets with fuel or power volatility.' },
    ],
  },
  {
    id: 'rival-blackglass',
    name: 'Blackglass Defense Fabrication',
    archetype: 'aggressive defense contractor',
    advantages: ['high aggression', 'strong contract bidding', 'durable control packages'],
    disadvantages: ['civilian reputation penalty', 'expensive compliance overhead'],
    preferredModuleCategories: ['structure', 'control', 'propulsion'],
    preferredVehicleClasses: ['patrol craft', 'armored utility', 'military support hull'],
    researchPreferences: ['structure', 'control', 'propulsion'],
    competitiveBehavior: 'Targets government and defense-adjacent contracts with ruthless pricing pressure.',
    pricingStrategy: 'strategic-underbid',
    licensingStrategy: 'restrictive licensing with heavy penalties',
    aggressionIndex: 0.95,
    contractBidAggression: 0.95,
    marketShareBias: 0.09,
    techLevelBehaviors: [
      { minTechLevel: 1, behavior: 'Bids hard on any security or patrol-adjacent work.' },
      { minTechLevel: 4, behavior: 'Uses reliability claims to force rivals out of official tenders.' },
      { minTechLevel: 7, behavior: 'Attempts market capture through exclusive procurement agreements.' },
    ],
  },
  {
    id: 'rival-bluepipe',
    name: 'Bluepipe Thermal Syndicate',
    archetype: 'thermal specialist supplier',
    advantages: ['excellent heat management', 'strong module licensing', 'low defect thermal packages'],
    disadvantages: ['weak complete hull catalog', 'limited cargo appeal'],
    preferredModuleCategories: ['thermal', 'power', 'utility'],
    preferredVehicleClasses: ['thermal retrofit', 'reactor support hull', 'industrial utility'],
    researchPreferences: ['thermal', 'power', 'manufacturing'],
    competitiveBehavior: 'Sells thermal solutions into everyone else’s overheating mistakes.',
    pricingStrategy: 'specialist-module-premium',
    licensingStrategy: 'aggressive module licensing',
    aggressionIndex: 0.58,
    contractBidAggression: 0.46,
    marketShareBias: 0.04,
    techLevelBehaviors: [
      { minTechLevel: 1, behavior: 'Supplies cheap coolers and radiator kits.' },
      { minTechLevel: 5, behavior: 'Licenses high-efficiency thermal loops to desperate drive firms.' },
      { minTechLevel: 8, behavior: 'Controls late-game high-heat system compatibility.' },
    ],
  },
  {
    id: 'rival-crownbulk',
    name: 'Crownbulk Freightworks',
    archetype: 'cargo capacity market leader',
    advantages: ['high cargo output', 'bulk contract expertise', 'cheap freight modules'],
    disadvantages: ['poor speed', 'mediocre automation'],
    preferredModuleCategories: ['cargo', 'structure', 'utility'],
    preferredVehicleClasses: ['bulk hauler', 'dockyard utility', 'freight carrier'],
    researchPreferences: ['cargo', 'structure', 'manufacturing'],
    competitiveBehavior: 'Wins cargo capacity bids with blunt, spacious, high-tonnage designs.',
    pricingStrategy: 'volume-contract',
    licensingStrategy: 'licenses cargo modules at low margin for market spread',
    aggressionIndex: 0.68,
    contractBidAggression: 0.82,
    marketShareBias: 0.1,
    techLevelBehaviors: [
      { minTechLevel: 1, behavior: 'Pursues every freight and volume contract it can reach.' },
      { minTechLevel: 4, behavior: 'Adds rugged structural cargo bays for remote markets.' },
      { minTechLevel: 7, behavior: 'Attempts to become default supplier for industrial logistics.' },
    ],
  },
  {
    id: 'rival-neonkeel',
    name: 'Neonkeel Experimental',
    archetype: 'volatile research disruptor',
    advantages: ['fast breakthrough chance', 'unusual tech branches', 'high upside designs'],
    disadvantages: ['high defect pressure', 'unstable production costs'],
    preferredModuleCategories: ['power', 'propulsion', 'control'],
    preferredVehicleClasses: ['prototype runner', 'experimental utility', 'special project craft'],
    researchPreferences: ['experimental power', 'advanced propulsion', 'automation'],
    competitiveBehavior: 'Launches strange high-upside designs that can either fail publicly or leapfrog the market.',
    pricingStrategy: 'volatile-premium',
    licensingStrategy: 'sells risky licenses early',
    aggressionIndex: 0.76,
    contractBidAggression: 0.52,
    marketShareBias: 0.03,
    techLevelBehaviors: [
      { minTechLevel: 1, behavior: 'Produces odd prototypes with inconsistent results.' },
      { minTechLevel: 5, behavior: 'Has a chance to leap ahead in one advanced branch.' },
      { minTechLevel: 8, behavior: 'Can become terrifying if early failures do not bankrupt it.' },
    ],
  },
  {
    id: 'rival-plainwell',
    name: 'Plainwell Standard Manufacturing',
    archetype: 'generic low-cost mass producer',
    advantages: ['low production cost', 'stable labor overhead', 'broad module coverage'],
    disadvantages: ['few standout technologies', 'weak premium margins'],
    preferredModuleCategories: ['utility', 'cargo', 'structure'],
    preferredVehicleClasses: ['standard utility', 'cheap courier', 'entry hauler'],
    researchPreferences: ['manufacturing', 'utility', 'cargo'],
    competitiveBehavior: 'Competes everywhere with boring cheap adequacy.',
    pricingStrategy: 'low-cost-standard',
    licensingStrategy: 'licenses older designs broadly',
    aggressionIndex: 0.6,
    contractBidAggression: 0.68,
    marketShareBias: 0.08,
    techLevelBehaviors: [
      { minTechLevel: 1, behavior: 'Fills the market with acceptable low-cost modules.' },
      { minTechLevel: 4, behavior: 'Uses manufacturing scale to suppress margins.' },
      { minTechLevel: 7, behavior: 'Becomes a volume threat if not out-teched.' },
    ],
  },
  {
    id: 'rival-ossuary',
    name: 'Ossuary Salvage Aerospace',
    archetype: 'scrap-efficient remanufacturer',
    advantages: ['low raw supply cost', 'strong salvage value', 'cheap repairs'],
    disadvantages: ['defect reputation', 'weak high-end contracts'],
    preferredModuleCategories: ['utility', 'structure', 'cargo'],
    preferredVehicleClasses: ['remanufactured hauler', 'salvage tug', 'cheap utility craft'],
    researchPreferences: ['manufacturing', 'structure', 'maintenance'],
    competitiveBehavior: 'Uses salvage economics and ugly refurbishing to survive price pressure.',
    pricingStrategy: 'deep-discount',
    licensingStrategy: 'buys distressed licenses and reuses them',
    aggressionIndex: 0.72,
    contractBidAggression: 0.8,
    marketShareBias: 0.05,
    techLevelBehaviors: [
      { minTechLevel: 1, behavior: 'Wins poor-client contracts with recycled hulls.' },
      { minTechLevel: 4, behavior: 'Improves reliability through remanufacturing discipline.' },
      { minTechLevel: 7, behavior: 'Becomes hard to kill due to salvage cash recovery.' },
    ],
  },
  {
    id: 'rival-aurex',
    name: 'Aurex Autonomous Systems',
    archetype: 'automation and control specialist',
    advantages: ['strong automation', 'lower crew burden', 'higher quality control'],
    disadvantages: ['high electronics demand', 'supply chain fragility'],
    preferredModuleCategories: ['control', 'utility', 'power'],
    preferredVehicleClasses: ['autonomous courier', 'survey vessel', 'remote utility craft'],
    researchPreferences: ['automation', 'control', 'electronics'],
    competitiveBehavior: 'Pushes autonomous and remote operation features into every market it enters.',
    pricingStrategy: 'automation-premium',
    licensingStrategy: 'licenses control modules selectively',
    aggressionIndex: 0.66,
    contractBidAggression: 0.56,
    marketShareBias: 0.06,
    techLevelBehaviors: [
      { minTechLevel: 1, behavior: 'Markets basic automation as labor savings.' },
      { minTechLevel: 5, behavior: 'Competes hard where crew cost matters.' },
      { minTechLevel: 8, behavior: 'Dominates remote operation markets if electronics supply holds.' },
    ],
  },
  {
    id: 'rival-heliox',
    name: 'Heliox Reactor Compact',
    archetype: 'reactor miniaturization firm',
    advantages: ['excellent power density', 'late-game reactor scaling', 'strong power licenses'],
    disadvantages: ['expensive parts', 'heat concentration risk'],
    preferredModuleCategories: ['power', 'thermal', 'control'],
    preferredVehicleClasses: ['compact utility', 'high-output courier', 'specialized power hull'],
    researchPreferences: ['reactor miniaturization', 'thermal', 'power stability'],
    competitiveBehavior: 'Wins when small hulls need oversized power output.',
    pricingStrategy: 'high-tech-power-premium',
    licensingStrategy: 'licenses obsolete reactors, guards new ones',
    aggressionIndex: 0.63,
    contractBidAggression: 0.5,
    marketShareBias: 0.04,
    techLevelBehaviors: [
      { minTechLevel: 1, behavior: 'Sells oversized, expensive power blocks.' },
      { minTechLevel: 5, behavior: 'Starts shrinking reactors into premium compact slots.' },
      { minTechLevel: 8, behavior: 'Becomes a key late-game power supplier.' },
    ],
  },
  {
    id: 'rival-vanta',
    name: 'Vanta Quiet Works',
    archetype: 'stealthy niche specialist',
    advantages: ['low market visibility', 'high niche margins', 'specialized control systems'],
    disadvantages: ['small volume', 'weak open competition'],
    preferredModuleCategories: ['control', 'thermal', 'utility'],
    preferredVehicleClasses: ['quiet courier', 'inspection craft', 'special access vessel'],
    researchPreferences: ['control', 'thermal', 'signature management'],
    competitiveBehavior: 'Avoids broad fights and quietly captures specialized high-margin niches.',
    pricingStrategy: 'niche-premium',
    licensingStrategy: 'rare and expensive licenses',
    aggressionIndex: 0.4,
    contractBidAggression: 0.36,
    marketShareBias: 0.02,
    techLevelBehaviors: [
      { minTechLevel: 1, behavior: 'Barely appears in public markets.' },
      { minTechLevel: 5, behavior: 'Captures obscure specialized contracts.' },
      { minTechLevel: 8, behavior: 'Can become a hidden high-margin rival.' },
    ],
  },
  {
    id: 'rival-hammerfall',
    name: 'Hammerfall Contract Yards',
    archetype: 'contract-first bulk bidder',
    advantages: ['fast contract response', 'low bid overhead', 'good production scheduling'],
    disadvantages: ['mediocre IP strategy', 'limited research ambition'],
    preferredModuleCategories: ['cargo', 'structure', 'propulsion'],
    preferredVehicleClasses: ['contract hauler', 'dock tug', 'municipal utility'],
    researchPreferences: ['manufacturing', 'cargo', 'propulsion'],
    competitiveBehavior: 'Lives on contracts and tries to keep factory capacity constantly occupied.',
    pricingStrategy: 'contract-underbid',
    licensingStrategy: 'buys licenses more often than it sells them',
    aggressionIndex: 0.78,
    contractBidAggression: 0.9,
    marketShareBias: 0.07,
    techLevelBehaviors: [
      { minTechLevel: 1, behavior: 'Bids almost everything that fits its catalog.' },
      { minTechLevel: 4, behavior: 'Optimizes factory scheduling and delivery reliability.' },
      { minTechLevel: 7, behavior: 'Can starve rivals by occupying contract boards.' },
    ],
  },
  {
    id: 'rival-lucidframe',
    name: 'Lucidframe Precision Hulls',
    archetype: 'quality and precision manufacturer',
    advantages: ['high quality', 'low defect rates', 'excellent documentation'],
    disadvantages: ['slow throughput', 'high labor cost'],
    preferredModuleCategories: ['structure', 'control', 'thermal'],
    preferredVehicleClasses: ['survey craft', 'precision utility', 'regulated industrial vessel'],
    researchPreferences: ['quality control', 'structure', 'control'],
    competitiveBehavior: 'Competes where inspection, quality, and low defect rates matter more than sticker price.',
    pricingStrategy: 'quality-premium',
    licensingStrategy: 'licenses certified designs at premium rates',
    aggressionIndex: 0.5,
    contractBidAggression: 0.44,
    marketShareBias: 0.04,
    techLevelBehaviors: [
      { minTechLevel: 1, behavior: 'Avoids high-volume low-margin work.' },
      { minTechLevel: 5, behavior: 'Targets regulated and inspection-heavy contracts.' },
      { minTechLevel: 8, behavior: 'Builds a reputation moat around certified reliability.' },
    ],
  },
  {
    id: 'rival-mothline',
    name: 'Mothline Remote Logistics',
    archetype: 'remote-market survival specialist',
    advantages: ['low maintenance burden in remote markets', 'rugged utility modules', 'supply route resilience'],
    disadvantages: ['higher base mass', 'less premium appeal'],
    preferredModuleCategories: ['utility', 'power', 'structure'],
    preferredVehicleClasses: ['remote utility', 'frontier hauler', 'repair craft'],
    researchPreferences: ['maintenance', 'power', 'utility'],
    competitiveBehavior: 'Wins contracts where distance, repairability, and poor infrastructure punish fragile designs.',
    pricingStrategy: 'remote-reliability',
    licensingStrategy: 'licenses field-service modules selectively',
    aggressionIndex: 0.57,
    contractBidAggression: 0.62,
    marketShareBias: 0.05,
    techLevelBehaviors: [
      { minTechLevel: 1, behavior: 'Builds ugly but serviceable frontier utility craft.' },
      { minTechLevel: 5, behavior: 'Competes hard in remote logistics and field support.' },
      { minTechLevel: 8, behavior: 'Dominates harsh-environment tenders.' },
    ],
  },
  {
    id: 'rival-orbitforge',
    name: 'Orbitforge Integrated Yards',
    archetype: 'balanced vertically integrated rival',
    advantages: ['broad tech coverage', 'stable supplier access', 'balanced portfolio'],
    disadvantages: ['few extreme specializations', 'bureaucratic cost creep'],
    preferredModuleCategories: ['power', 'cargo', 'control', 'structure'],
    preferredVehicleClasses: ['utility vessel', 'courier', 'hauler', 'support craft'],
    researchPreferences: ['balanced systems', 'manufacturing', 'supply chain'],
    competitiveBehavior: 'Maintains broad market coverage and adapts to whichever sector is profitable.',
    pricingStrategy: 'balanced-portfolio',
    licensingStrategy: 'licenses mature non-core modules',
    aggressionIndex: 0.65,
    contractBidAggression: 0.64,
    marketShareBias: 0.09,
    techLevelBehaviors: [
      { minTechLevel: 1, behavior: 'Competes broadly without overcommitting.' },
      { minTechLevel: 5, behavior: 'Uses vertical integration to stabilize costs.' },
      { minTechLevel: 8, behavior: 'Can become a general-market superpower.' },
    ],
  },
];

export function rivalTemplateById(templateId) {
  return rivalCompanyTemplates.find((template) => template.id === templateId);
}

export function rivalTemplatesForDifficulty(difficultyId = 'normal') {
  return rivalCompanyTemplates.slice(0, rivalCountForDifficulty(difficultyId));
}

export function describeRivalBehaviorAtTechLevel(template, techLevel = 1) {
  const behaviors = [...(template.techLevelBehaviors ?? [])]
    .filter((entry) => techLevel >= entry.minTechLevel)
    .sort((a, b) => b.minTechLevel - a.minTechLevel);
  return behaviors[0]?.behavior ?? template.competitiveBehavior;
}
